version: '3.9'
services:
  proxy:
    image: rongem/cmdb:proxy
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile.proxy
      context: .
    depends_on:
      - frontend
      - backend
  frontend:
    image: rongem/cmdb:frontend
    build:
      dockerfile: Dockerfile.frontend
      context: .
#    restart: always
    depends_on:
      - backend
  backend:
    image: rongem/cmdb:backend
    build:
      dockerfile: Dockerfile.backend
      context: .
    environment:
      - MONGODB_URI
      - AUTH_MODE
      - JWT_SERVER_KEY
      - SALT
