version: '3.8'
services:
  cmdb:
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile.cmdb.dev
      context: ./ng-frontend
    volumes:
      - /usr/app/node_modules
      - ./ng-frontend:/usr/app
    depends_on:
      - backend
  dcman:
    ports:
      - 81:80
    build:
      dockerfile: Dockerfile.dcman.dev
      context: ./ng-frontend
    volumes:
      - /usr/app/node_modules
      - ./ng-frontend:/usr/app
    depends_on:
      - backend
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./njs-backend
    volumes:
      - /usr/app/node_modules
      - ./njs-backend:/usr/app
    environment:
      - MONGODB_URI
      - AUTH_MODE
      - JWT_SERVER_KEY
      - SALT
