FROM node:14 AS build
WORKDIR /usr/app

COPY ./ng-frontend/package*.json ./
#RUN npm update -g # only if image was too old
RUN npm install
COPY ./ng-frontend/ ./
RUN npm run build:all

FROM nginx
WORKDIR /usr/app
COPY --from=build /usr/app/dist/cmdb /usr/share/nginx/html/cmdb
COPY --from=build /usr/app/dist/dcman /usr/share/nginx/html/dcman
COPY ./nginx/angular.conf /etc/nginx/conf.d/default.conf
