// REST API URL constants
// - MetaData
export const METADATA = 'MetaData';
export const USER = 'User/';
export const USERS = 'Users';
export const ATTRIBUTETYPE = 'AttributeType/';
export const ATTRIBUTETYPES = 'AttributeTypes/';
export const CONVERTTOITEMTYPE = '/ConvertToItemType';
export const ATTRIBUTEGROUP = 'AttributeGroup/';
export const ATTRIBUTEGROUPS = 'AttributeGroups/';
export const ITEMTYPE = 'ItemType/';
export const ITEMTYPES = 'ItemType/';
export const CONNECTIONTYPE = 'ConnectionType/';
export const CONNECTIONTYPES = 'ConnectionTypes/';
export const CONNECTIONRULE = 'ConnectionRule/';
export const CONNECTIONRULES = 'ConnectionRules/';
export const CORRESPONDINGVALUESOFTYPE = '/CorrespondingValuesOfType';

// - Data
export const ATTRIBUTES = '/Attributes';
export const AVAILABLE = 'Available/';
export const BYTYPE = 'ByType/';
export const BYTYPES = 'ByTypes/';
export const CONFIGURATIONITEM = 'ConfigurationItem/';
export const CONFIGURATIONITEMS = 'ConfigurationItems/';
export const CONNECTABLEASLOWERITEM = 'ConnectableAsLowerItem/';
export const CONNECTION = 'Connection/';
export const CONNECTIONS = '/Connections';
export const COUNT = '/Count';
export const COUNTATTRIBUTES = '/CountAttributes';
export const DESCRIPTION = '/description';
export const FULL = '/Full';
export const HISTORY = '/history';
export const IMPORTCONVERTFILETOTABLE = 'Import/ConvertFileToTable';
export const IMPORTDATATABLE = 'Import/DataTable';
export const ITEM = 'Item/';
export const NAME = '/name/';
export const PROPOSALS = 'Proposals/';
export const RECENT = 'Recent/';
export const RESPONSIBILITY = '/Responsibility';
export const RULE = '/Rule/';
export const SEARCHTEXT = 'search/';
export const TYPE = 'type/';
