# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        path: temp-src
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build NodeJS/Express backend
      run: |
           cd temp-src/njs-backend
           npm ci
           npm run build --if-present
    - name: Move results and cleanup
      run: |
           mv temp-src/njs-backend/dist .
           rm -fr temp-src
           ls -l
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: dist
#    - run: npm test
